services:
  db:
    image: postgres:latest
    container_name: db_cproject
    environment:
      - ENV=PRODUCTION
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - cproject-network
    volumes:
      - db_storage:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - 3000:3000
    networks:
      - cproject-network
    env_file:
      - .env
networks:
  cproject-network:
  
volumes:
  db_storage:
    driver: local
  server_storage:
    driver: local
